# Generated by Django 4.0.2 on 2022-02-08 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drivingschool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivingschool.group'),
        ),
        migrations.AddField(
            model_name='student',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivingschool.instructor'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduletheory',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivingschool.group'),
        ),
        migrations.AddField(
            model_name='schedulepractice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivingschool.student'),
        ),
        migrations.AddField(
            model_name='lessontheory',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivingschool.group'),
        ),
        migrations.AddField(
            model_name='lessontheory',
            name='topic',
            field=models.ManyToManyField(to='drivingschool.TopicTheory'),
        ),
        migrations.AddField(
            model_name='lessontheory',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivingschool.tutor'),
        ),
        migrations.AddField(
            model_name='lessonpractice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivingschool.student'),
        ),
        migrations.AddField(
            model_name='lessonpractice',
            name='topic',
            field=models.ManyToManyField(to='drivingschool.TopicPractice'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivingschool.car'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivingschool.tutor'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivingschool.carbrand'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivingschool.carmodel'),
        ),
    ]
