# Generated by Django 4.0.2 on 2022-03-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivingschool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletheory',
            name='position',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth'), (6, 'Sixth')], default=1, verbose_name='Позиция'),
            preserve_default=False,
        ),
    ]
