# Generated by Django 4.0.2 on 2022-02-16 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drivingschool', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabinet',
            options={'verbose_name': 'Кабинет', 'verbose_name_plural': 'Кабинеты'},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='carbrand',
            options={'verbose_name': 'Марка авто', 'verbose_name_plural': 'Марки авто'},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'Модель авто', 'verbose_name_plural': 'Модели авто'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name': 'Инструктор', 'verbose_name_plural': 'Инструкторы'},
        ),
        migrations.AlterModelOptions(
            name='lessonpractice',
            options={'verbose_name': 'Занятие практическое', 'verbose_name_plural': 'Занятия практические'},
        ),
        migrations.AlterModelOptions(
            name='lessontheory',
            options={'verbose_name': 'Занятие теоритическое', 'verbose_name_plural': 'Занятия теоритические'},
        ),
        migrations.AlterModelOptions(
            name='schedulepractice',
            options={'verbose_name': 'Расписание прак. занятий', 'verbose_name_plural': 'Расписания прак. занятий'},
        ),
        migrations.AlterModelOptions(
            name='scheduletheory',
            options={'verbose_name': 'Расписание теор. занятий', 'verbose_name_plural': 'Расписания теор. занятий'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Обучающийся', 'verbose_name_plural': 'Обучающиеся'},
        ),
        migrations.AlterModelOptions(
            name='topicpractice',
            options={'verbose_name': 'Тема практическая', 'verbose_name_plural': 'Темы практические'},
        ),
        migrations.AlterModelOptions(
            name='topictheory',
            options={'verbose_name': 'Тема теоритическая', 'verbose_name_plural': 'Темы теоритические'},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='cabinet',
            field=models.CharField(max_length=31, verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivingschool.carbrand', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivingschool.carmodel', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='state_number',
            field=models.CharField(max_length=15, verbose_name='Госномер'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.IntegerField(choices=[(0, 'Механика'), (1, 'Автомат')], verbose_name='Коробка передач'),
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='name',
            field=models.CharField(max_length=127, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='name',
            field=models.CharField(max_length=127, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=31, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='group',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivingschool.tutor', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivingschool.car', verbose_name='Авто'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='lessonpractice',
            name='started_at',
            field=models.DateTimeField(blank=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='lessonpractice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivingschool.student', verbose_name='Обучающийся'),
        ),
        migrations.AlterField(
            model_name='lessonpractice',
            name='topic',
            field=models.ManyToManyField(to='drivingschool.TopicPractice', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='lessontheory',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivingschool.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='lessontheory',
            name='started_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='lessontheory',
            name='topic',
            field=models.ManyToManyField(to='drivingschool.TopicTheory', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='lessontheory',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivingschool.tutor', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='schedulepractice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivingschool.student', verbose_name='Обучающийся'),
        ),
        migrations.AlterField(
            model_name='schedulepractice',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='scheduletheory',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivingschool.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='scheduletheory',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivingschool.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='student',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivingschool.instructor', verbose_name='Инструктор'),
        ),
        migrations.AlterField(
            model_name='student',
            name='license_category',
            field=models.CharField(choices=[('А', 'A'), ('Б', 'B'), ('В', 'C'), ('Г', 'D'), ('Д', 'E')], max_length=1, verbose_name='Категория прав'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='topicpractice',
            name='name',
            field=models.CharField(max_length=127, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='topictheory',
            name='name',
            field=models.CharField(max_length=127, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='cabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivingschool.cabinet', verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(choices=[(5, 'Отлично'), (4, 'Хорошо'), (3, 'Удовлетворительно'), (2, 'Неудовлетворительно'), (1, 'Кол')], verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Поставлена')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменена')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivingschool.student', verbose_name='Обучающийся')),
            ],
        ),
    ]
