# Generated by Django 4.0.2 on 2022-02-06 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivingschool', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
