# Generated by Django 4.0.2 on 2022-03-12 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivingschool', '0002_scheduletheory_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduletheory',
            options={'ordering': ('group', 'weekday', 'position'), 'verbose_name': 'Расписание теор. занятий', 'verbose_name_plural': 'Расписания теор. занятий'},
        ),
        migrations.AddField(
            model_name='scheduletheory',
            name='substitute_tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drivingschool.tutor', verbose_name='Учитель на замену'),
        ),
        migrations.AlterField(
            model_name='scheduletheory',
            name='position',
            field=models.IntegerField(choices=[(1, '9:00 - 10:30'), (2, '10:40 - 12:10'), (3, '12:50 - 14:20'), (4, '14:30 - 16:00'), (5, '16:30 - 18:00'), (6, '18:30 - 20:00')], verbose_name='Позиция'),
        ),
    ]
