# Generated by Django 4.0.2 on 2022-03-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivingschool', '0003_alter_scheduletheory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='avatars/default-profile.png', upload_to='avatars/', verbose_name='Фото'),
        ),
    ]
