# Generated by Django 4.0.2 on 2022-03-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivingschool', '0003_alter_cabinet_options_alter_car_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='mark',
            options={'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
    ]
