# Generated by Django 4.0.2 on 2022-03-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivingschool', '0004_callapplication_alter_mark_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callapplication',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterField(
            model_name='callapplication',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='callapplication',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
    ]
