# Generated by Django 4.0.2 on 2022-03-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivingschool', '0004_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulepractice',
            name='position',
            field=models.IntegerField(choices=[(1, '9:00 - 10:30'), (2, '10:40 - 12:10'), (3, '12:50 - 14:20'), (4, '14:30 - 16:00'), (5, '16:30 - 18:00'), (6, '18:30 - 20:00')], default=1, verbose_name='Время'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scheduletheory',
            name='position',
            field=models.IntegerField(choices=[(1, '9:00 - 10:30'), (2, '10:40 - 12:10'), (3, '12:50 - 14:20'), (4, '14:30 - 16:00'), (5, '16:30 - 18:00'), (6, '18:30 - 20:00')], verbose_name='Время'),
        ),
    ]
