# Generated by Django 4.0.2 on 2022-04-06 07:12

from django.db import migrations, models
import drivingschool.models


class Migration(migrations.Migration):

    dependencies = [
        ('drivingschool', '0005_schedulepractice_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=127, validators=[drivingschool.models.validate_phone_number], verbose_name='Телефон'),
        ),
    ]
